Django/mysite/forum/urls.py
from django.urls import path
from . import views 

app_name = "forum"
urlpatterns = [
    path('', views.index, name='index'),
    path('<topic>/', views.forum, name = "forum")
]

Django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls")),
    path("forum/", include("forum.urls")),
]

Django/mysite/polls/urls.py
from django.urls import path 
from . import views

app_name = "polls"

urlpatterns = [
    path("", views.index, name="index"),
    #path("result/", views.result, name="result"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

Django/mysite/forum/models.py
from django.db import models
# Create your models here.

class Topic(models.Model):
    name = models.CharField("topic name", max_length = 200)

    def __str__(self):
        return self.name

class Message(models.Model):
    def __str__(self):
        return self.content
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
    content = models.CharField("message", max_length = 1000)
    created_at = models.DateTimeField(auto_now_add=True)

Django/mysite/polls/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    def __str__(self):
        return self.question_text
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

class Choice(models.Model):
    def __str__(self):
        return self.choice_text
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

Django/mysite/forum/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Topic, Message

# Create your views here.

def index(request):
    topic_list = Topic.objects.all()
    context = {
        "topic_list": topic_list,
    }
    return render(request, "forum/index.html", context)


def forum(request, topic):
    topic_obj = Topic.objects.get(name=topic)
    print(topic_obj)
    msgs= Message.objects.filter(topic=topic_obj).order_by("created_at")
    

    new_message = request.POST['tweet']
    print(new_message)
    message = Message.objects.create(topic=topic_obj, content=new_message)
    print(message)
    # return redirect('forum:forum', topic=topic_obj.name)


        

    context = {
        "topic": topic_obj,
        "messages": msgs
    }

    return render(request, "forum/forum.html", context)

Django/mysite/polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import  HttpResponse
from .models import Question, Choice

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {
        "latest_question_list": latest_question_list,
    }
    return render(request, "polls/index.html", context)





def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    
    context = {
        "question": question,
    }

    return render(request, "polls/detail.html", context)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {
        "question": question
    }
    return render(request, "polls/results.html", context)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/detail.html", context = {
            "question": question,
            "error_message": "You have not voted yet."
        })
    else:
        selected_choice.votes += 1 
        selected_choice.save()

        return redirect('polls:results', question.id)

Django/mysite/forum/templates/forum/forum.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title> Forum </title>
    </head>

    <body>
        <h1>{{topic}} Forum </h1>

        <h2>Messages</h2>
        {% if messages %}
        {% for msg in messages %}
        {{ msg.content }} posted on {{ msg.created_at }} <br>
        {% endfor %}
        {% endif %}
        <br>

        <form action="{% url 'forum:forum' topic.name %}" method = "POST">
            {% csrf_token %}
            <input type="text" name="tweet">
            <input type="submit", value = "submission">
        </form>
        <br>
        <a href="{% url 'forum:index' %}"> Home </a>

    </body>
</html>

Django/mysite/forum/templates/forum/index.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        {%  load static %}
        <meta charset="UTF-8">
        <title> Forum</title>
        <link rel="stylesheet" type="text/css" href="{% static 'forum/css/index.css' %}" />
        <!--pyton manage.py runserver-->
        <!--http://127.0.0.1:8000/forum/-->
    </head>

    <body>
        {% if topic_list %}
        {% for topic in topic_list %}
        <ul>
            <a href="{% url 'forum:forum' topic.name %}">{{topic.name}}</a>
        </ul>
        {% endfor %}
        {% endif %}
        
    </body>

Django/mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title> Polls application </title>
    </head>

    <body>

        <form action="{% url 'polls:vote' question.id %}" method="POST">
            {% csrf_token %}

            <div>
                <h1>{{question.question_text}}</h1>
                {% if error_message %}
                <p><strong>{{error_message}}</strong></p>
                {% endif %}

            {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}">
            <label for="choice{{ forloop.counter }}">
                {{choice.choice_text}}
            </label>
            <br>
            {% endfor %}

            </div>
            <input type="submit" value="Vote">
        </form>
        <h1>{{ question.question_text }}</h1>
        <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }}</li>
        {% endfor %}
        </ul>

    </body>
</html>

Django/mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title> Polls Application</title>
    </head>

    <body>
        {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
            <li>
                <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
            </li>
            {% endfor %}
        </ul>

        {% else %}
        <p>No polls are available</p>
        {% endif %}
    </body>
</html>

Django/mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

{% if question.choice_set %}
{% for choice in question.choice_set.all %}
<ul>
    {{ choice.choice_text }} : {{ choice.votes }}
</ul>
{% endfor %}
{% endif %}

<a href="{% url 'polls:detail' question.id %}">Vote again</a>